service:
  name: childAssets

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
  serverless-iam-roles-per-function:
    defaultInherit: true
  prune:
    automatic: true
    number: 3
  profiles:
    dev: default
  regions:
    dev: eu-central-1

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-prune-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: ${opt:region, self:custom.regions.${self:provider.stage}}
  memorySize: 128
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}

functions:
  getChilds:
    handler: src/getChilds.index
    events:
      - http:
          path: getChilds
          method: post
  folderStructure:
    handler: src/folderStructure.index
    events:
      - http:
          path: getFolderStructure
          method: post
  searchAssets:
    handler: src/searchAssets.index
    events:
      - http:
          path: searchAssets
          method: post
  replaceId:
    handler: src/replaceId.index
    events:
      - http:
          path: replaceId
          method: post
  elementMapping:
    handler: src/elementMapping.index
    events:
      - http:
          path: elementMapping
          method: post
